development:
  host: localhost
  database: rails_gridfs_demo_development

test:
  host: localhost
  database: rails_gridfs_demo_test

production:
  host: localhost
  database: rails_gridfs_demo_production
